### ISSUE TITLE
issue1

### ISSUE THREAD

**Issue by SharkyPNV** [SharkyPNV/MathematicalTest#1]
![Условие](https://user-images.githubusercontent.com/104147517/166244561-84312ec7-1eb1-4992-b56d-4176ba03cef4.jpeg)

- [x] Жук = 
- [x] Пчела = 
- [x] Муравей =

**Comment by SharkyPNV** [comment]
@VenaPPS

**Comment by VenaPPS** [comment]
@venapps хочу взять задачу на себя
